# Generated by Django 5.1.5 on 2025-01-17 11:39

import comments.utils
import comments.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_page",
                    models.URLField(blank=True, null=True, verbose_name="home page"),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[comments.validators.xhtml_validator],
                        verbose_name="text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "attached_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=comments.utils.comment_image_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "gif", "png"]
                            )
                        ],
                        verbose_name="attached image",
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=comments.utils.comment_text_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            ),
                            comments.validators.validate_file_size,
                        ],
                        verbose_name="attached file",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                        verbose_name="parent comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
